stages:
    - build

build_docker:
    stage: build
    tags:
        - docker
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --tag="$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
        - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    when: on_success

build_latex:
    stage: build
    image: docker.gitlab.tab-e.de/docker/docker-images/latex:wheezy
    script:
        - cd docs
        - pdflatex dokumentation.tex
    artifacts:
        name: "Dokumentation"
        paths:
            - "docs/*.pdf"
        expire_in: "2 yrs"
