stages:
    - build_docker

build_docker:
    stage: build_docker
    tags:
        - docker
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --tag="$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" code/.
        - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    when: on_success
